language: java

sudo: false

install: true

jdk:
  - openjdk8

notifications:
  email:
    recipients:
      - javendev@126.com
    on_success: never
    on_failure: always

cache:
  directories:
    - '$HOME/.m2'

script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
